# Copyright 2021-2024 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: "Make release"

on:
  push:
    tags:
      - "openssl-**"

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
      with:
        fetch-depth: 1
        ref: ${{ github.ref_name }}
        path: ${{ github.ref_name }}
    - name: "Prepare assets"
      run: |
        cd ${{ github.ref_name }}
        ./util/mktar.sh
        mkdir assets && mv openssl-3.3.3-dev.tar.gz assets/ && cd assets
        openssl sha1 < openssl-3.3.3-dev.tar.gz | cut -d " " -f 2 > ${{ github.ref_name }}.tar.gz.sha1
        openssl sha256 < openssl-3.3.3-dev.tar.gz | cut -d " " -f 2 > ${{ github.ref_name }}.tar.gz.sha256
    - name: "Create release"
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        ls -l
        VERSION=$(echo ${{ github.ref_name }} | cut -d "-" -f 2-)
        gh release create ${{ github.ref_name }} -t "OpenSSL $VERSION" -d --notes " " -R ${{ github.repository }} assets/*
